//@ts-ignore
import { ERLayout } from "@antv/layout";
//const { ERLayout } = "@antv/layout";

console.log('ERLayout')
console.log(ERLayout)


const cells = [];
const edges = [];
const nodes = [];

const ERLayoutInstance = new ERLayout({
    nodes,
    edges,
    nodeMinGap: 120,
});

clearEditor();

ERLayoutInstance.execute().then((res) => {
    const x6Workflow = formatToX6(dummyData);
    graph.resetCells(x6Workflow);
    graph.zoomToFit({ padding: 10, maxScale: 1 });
});

